[package]
name = "limes"
version = "0.2.0"
edition = "2021"
authors = ["Enrico Fiasco e.fiasco@studenti.unipi.it"]
description = "Limes is a FaaS executor for Wasm Modules with support for SLLM's and LLM's"

[[bin]]
name = "limes-server"
path = "src/main.rs"

[[bin]]
name = "limes-run"
path = "src/limes-run.rs"

[dependencies]
anyhow = "1.0.97"
async-trait = "0.1.88"
atoi = "2.0.0"
axum = "0.7"
bytes = "1.11.1"
clap = { version = "4.5.37", features = ["derive"] }
crc32fast = "1.4.2"
env_logger = "0.11.8"
json = "0.12.4"
llama-cpp-2 = "0.1.135"
llama-cpp-sys-2 = "0.1.135"
log = "0.4.27"
nanoid = "0.4.0"
regex = "1.12.3"
rig-core = "0.32.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.44.1", features = ["full"] }
uuid = { version = "1.15.1", features = ["v4"] }
wasmtime = "42.0.1"
wasmtime-wasi = "42.0.1"
